package id.ac.poliban.mi.firda.listpahlawan;

import java.util.ArrayList;
import java.util.List;

public class PahlawanData {
    static List<Pahlawan> getAllPahlawan(){
        List<Pahlawan> data = new ArrayList<>();
        {
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg/220px-Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg", "Ki Hadjar Dewantara", "Raden Mas Soewardi Soerjaningrat (EBI: Suwardi Suryaningrat, sejak 1922 menjadi Ki Hadjar Dewantara, EBI: Ki Hajar Dewantara, beberapa menuliskan bunyi bahasa Jawanya dengan Ki Hajar Dewantoro; lahir di Pakualaman, 2 Mei 1889 – meninggal di Yogyakarta, 26 April 1959 pada umur 69 tahun;[1] selanjutnya disingkat sebagai \"Soewardi\" atau \"KHD\") adalah aktivis pergerakan kemerdekaan Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda. Ia adalah pendiri Perguruan Taman Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi para pribumi untuk bisa memperoleh hak pendidikan seperti halnya para priyayi maupun orang-orang Belanda."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg/200px-COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg", "R.A. Kartini", "Raden Adjeng Kartini (lahir di Jepara, Hindia Belanda, 21 April 1879 – meninggal di Rembang, Hindia Belanda, 17 September 1904 pada umur 25 tahun) atau sebenarnya lebih tepat disebut Raden Ayu Kartini[1] adalah seorang tokoh Jawa dan Pahlawan Nasional Indonesia. Kartini dikenal sebagai pelopor kebangkitan perempuan pribumi."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/thumb/c/c8/Pangeran_Antasari_Museum_Lambung_Mangkurat.JPG/220px-Pangeran_Antasari_Museum_Lambung_Mangkurat.JPG", "Pangeran Antasari", "Pangeran Antasari (lahir di Kayu Tangi, Kesultanan Banjar, 1797[1][2] atau 1809[3][4][5][6] – meninggal di Bayan Begok, Hindia Belanda, 11 Oktober 1862 pada umur 53 tahun) adalah seorang Pahlawan Nasional Indonesia.\n" + "\n" + "Ia adalah Sultan Banjar.[7] Pada 14 Maret 1862, dia dinobatkan sebagai pimpinan pemerintahan tertinggi di Kesultanan Banjar (Sultan Banjar) dengan menyandang gelar Panembahan Amiruddin Khalifatul Mukminin dihadapan para kepala suku Dayak dan adipati (gubernur) penguasa wilayah Dusun Atas, Kapuas dan Kahayan yaitu Tumenggung Surapati/Tumenggung Yang Pati Jaya Raja.[8]"));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Bung_Tomo.jpg/220px-Bung_Tomo.jpg", "Sutomo", "Sutomo (lahir di Surabaya, Jawa Timur, 3 Oktober 1920 – meninggal di Padang Arafah, Arab Saudi, 7 Oktober 1981 pada umur 61 tahun)[1] lebih dikenal dengan sapaan akrab oleh rakyat sebagai Bung Tomo, adalah pahlawan yang terkenal karena peranannya dalam membangkitkan semangat rakyat untuk melawan kembalinya penjajah Belanda melalui tentara NICA, yang berakhir dengan pertempuran 10 November 1945 yang hingga kini diperingati sebagai Hari Pahlawan."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Tjoet_Nya%27_Dhien.jpg/220px-Tjoet_Nya%27_Dhien.jpg", "Cut Nyak Dhien", "Cut Nyak Dhien (ejaan lama: Tjoet Nja' Dhien, Lampadang, Kerajaan Aceh, 1848 – Sumedang, Jawa Barat, 6 November 1908; dimakamkan di Gunung Puyuh, Sumedang) adalah seorang Pahlawan Nasional Indonesia dari Aceh yang berjuang melawan Belanda pada masa Perang Aceh. Setelah wilayah VI Mukim diserang, ia mengungsi, sementara suaminya Ibrahim Lamnga bertempur melawan Belanda. Tewasnya Ibrahim Lamnga di Gle Tarum pada tanggal 29 Juni 1878 kemudian menyeret Cut Nyak Dhien lebih jauh dalam perlawanannya terhadap Belanda."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Oto_Iskandar_di_Nata_Youth.jpg/280px-Oto_Iskandar_di_Nata_Youth.jpg", "Raden Otto Iskandardinata", "Raden Otto Iskandardinata (Sunda: ᮛ᮪ᮓ᮪. ᮇᮒ᮪ᮒᮧ ᮄᮞ᮪ᮊᮔ᮪ᮓᮁᮓᮤᮔᮒ, Latin: Rd. Otto Iskandardinata; lahir di Bandung, Jawa Barat, 31 Maret 1897 – meninggal di Mauk, Tangerang, Banten, 20 Desember 1945 pada umur 48 tahun) adalah salah satu Pahlawan Nasional Indonesia. Ia mendapat nama julukan si Jalak Harupat"));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Tendean.jpg/220px-Tendean.jpg", "Pierre Andries Tendean", "Kapten Czi. (Anumerta) Pierre Andries Tendean[1] (lahir 21 Februari 1939 – meninggal 1 Oktober 1965 pada umur 26 tahun) adalah seorang perwira militer Indonesia yang menjadi salah satu korban peristiwa Gerakan 30 September pada tahun 1965. Mengawali karier militer dengan menjadi intelijen dan kemudian ditunjuk sebagai Ajudan Jenderal Besar TNI Abdul Haris Nasution menggantikan Kapten Kav Adolf Gustaf Manullang ajudan Pak Nas, yang gugur dalam misi perdamaian di Kongo Afrika tahun 1963.[butuh rujukan] dengan pangkat Letnan Satu Czi, ia dipromosikan menjadi Kapten Anumerta setelah kematiannya. Tendean dimakamkan di Taman Makam Pahlawan Kalibata dan bersama enam perwira korban Gerakan 30 September lainnya, ia ditetapkan sebagai Pahlawan Revolusi Indonesia pada tanggal 5 Oktober 1965"));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sudirman.jpg/220px-Sudirman.jpg", "Soedirman", "Jenderal Besar Raden Soedirman (EYD: Sudirman; lahir 24 Januari 1916 – meninggal 29 Januari 1950 pada umur 34 tahun[a]) adalah seorang perwira tinggi Indonesia pada masa Revolusi Nasional Indonesia. Sebagai panglima besar Tentara Nasional Indonesia pertama, ia adalah sosok yang dihormati di Indonesia. Terlahir dari pasangan rakyat biasa di Purbalingga, Hindia Belanda, Soedirman diadopsi oleh pamannya yang seorang priyayi. Setelah keluarganya pindah ke Cilacap pada tahun 1916, Soedirman tumbuh menjadi seorang siswa rajin; ia sangat aktif dalam kegiatan ekstrakurikuler, termasuk mengikuti program kepanduan yang dijalankan oleh organisasi Islam Muhammadiyah. Saat di sekolah menengah, Soedirman mulai menunjukkan kemampuannya dalam memimpin dan berorganisasi, dan dihormati oleh masyarakat karena ketaatannya pada Islam. Setelah berhenti kuliah keguruan, pada 1936 ia mulai bekerja sebagai seorang guru, dan kemudian menjadi kepala sekolah, di sekolah dasar Muhammadiyah; ia juga aktif dalam kegiatan Muhammadiyah lainnya dan menjadi pemimpin Kelompok Pemuda Muhammadiyah pada tahun 1937. Setelah Jepang menduduki Hindia Belanda pada 1942, Soedirman tetap mengajar. Pada tahun 1944, ia bergabung dengan tentara Pembela Tanah Air (PETA) yang disponsori Jepang, menjabat sebagai komandan batalion di Banyumas. Selama menjabat, Soedirman bersama rekannya sesama prajurit melakukan pemberontakan, namun kemudian diasingkan ke Bogor."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/thumb/2/2d/Sultan_Agung.jpg/220px-Sultan_Agung.jpg", "Sultan Agung Adi Prabu Hanyakrakusuma", "Sultan Agung Adi Prabu Hanyakrakusuma (Bahasa Jawa: ꦯꦸꦭ꧀ꦠꦤ꧀ꦲꦒꦸꦁꦲꦢꦶꦦꦿꦧꦸꦲꦚꦏꦿꦏꦸꦱꦸꦩ, Sultan Agung Adi Prabu Hanyokrokusumo, lahir: Kotagede, Kesultanan Mataram, 1593 - wafat: Karta (Pleret, Bantul), Kesultanan Mataram, 1645) adalah Sultan ketiga Kesultanan Mataram yang memerintah pada periode tahun 1613-1645. Di bawah kepemimpinannya, Mataram berkembang menjadi kerajaan terbesar di Jawa dan Nusantara pada saat itu."));
            data.add(new Pahlawan("https://upload.wikimedia.org/wikipedia/id/thumb/3/34/Sultan-dg-raja.jpg/220px-Sultan-dg-raja.jpg", "Andi Sultan Daeng Radja", "Haji Andi Sultan Daeng Radja (lahir di Matekko, Gantarang, Bulukumba, 20 Mei 1894 – meninggal di Rumah Sakit Pelamonia Makassar, Sulawesi Selatan, 17 Mei 1963 pada umur 68 tahun) adalah seorang tokoh kemerdekaan Indonesia dan pahlawan nasional dari Sulawesi Selatan. Ia adalah putra pertama pasangan Passari Petta Tanra Karaeng Gantarang dan Andi Ninong. Semasa muda, Sultan Daeng Radja dikenal taat beribadah dan aktif dalam kegiatan Muhamamadiyah. Ia merupakan pendiri Masjid Tua di Ponre yang pada jamannya terbesar di Sulawesi Selatan."));

        }
        return data;
    }
}
